modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="toolsplus"
version="1.0.1"
displayName="Tools+"
description='''Tools+ provides server enchanting utilities and per-player language settings.'''

[[dependencies.toolsplus]]
modId="forge"
mandatory=true
versionRange="[36.2.34,)"
ordering="NONE"
side="BOTH"

[[dependencies.toolsplus]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"